### PR TITLE
Added custom PolyVertexEditTool

### PR DESCRIPTION
**Pull request by philippjfr**
Adds customized PolyEditTool which supports dragging shared nodes and allows coloring feature vertices differently from regular vertices.

### CODE REVIEW

**Comment by philippjfr** [comment]
@kcpevey Would be great if you could try this out.

**Comment by kcpevey** [comment]
I think this is heading in the right direction. As expected, it still needs more work which I think you can proceed on.   
  
Some bugs I noticed:   
- it seems to randomly decide to finish the polygon and start a new one, despite me only single-clicking.   
- it randomly snaps to vertices cuts polygons even though I'm click a location very far from the node in which it snapped. 
- sometimes it correctly cuts the polygon (maybe the first cut?) but if I continue drawing, I eventually end up with overlapping polygons - something I'm hoping to avoid  
  
I didn't see the different color vertices/nodes, but that's probably because I wasn't sure how to trigger that visualization.

**Comment by philippjfr** [comment]
@kcpevey This is ready for you to try out again.

**Comment by kcpevey** [comment]
@philippjfr I'm seeing some strange behavior. It feels like there is a bug or two in there somewhere but I couldn't get a recipe to reproduce most things:  
* deleting is a little buggy - sometimes deleting a path leaves behind a stray node - seems random, this has been a bug for a long time I think
* at some point, it seemed to have swapped the "double-click makes an endpoint" and "single click makes a vertex". I managed to get a vertex as an endpoint to a path
* draw a multi-line with multiple connection points doesn't trigger an update to node - I'm pretty sure 
this is due to the swapped bug above
* I have two videos that I can show you on the call tomorrow that demo some usability stuff.  
  
Questions:  
* is it possible to drag an existing path endpoint and attach it (via snapping to an existing node)?
*  is there a plan to allow for adding vertices/adding nodes to midpoint of line?

* eventually we need a 'clean' tool (perhaps part of polygon 'build' tool) that takes all the paths that a user has drawn and at every location. Probably need to add that to the roadmap for the 'building a polygon from multiple paths' task.

**Comment by kcpevey** [comment]
Also, do we have a roadmap for this task? It seems to have come a long way since #272 .

**Comment by philippjfr** [comment]
>is there a plan to allow for adding vertices/adding nodes to midpoint of line?

By clicking somewhere on an existing line.

>eventually we need a 'clean' tool (perhaps part of polygon 'build' tool) that takes all the paths that a user has drawn and at every location.

Should consider whether this is a tool in the toolbar or a separate button in the polygon builder class.

Tasks: 

- [ ] The VertexEditTool should not allow selecting lines with single click
- [ ] Use zero-alpha large line width on nodes to improve hit testing
- [ ] Make new issue outlining a roadmap for drawing tool enhancements

**Pull request merged**
