### PR TITLE
Meshing update

### PR DESCRIPTION
**Pull request by kcpevey**
removes filigree dependency and replaces with xmsmesh

### CODE REVIEW

**Comment by philippjfr** [comment]
Just a few questions and requests:

1. Should we also delete filigree.py? 
2. Could you update doc/user_guide/index.rst replacing Specifying_Meshes with Generating_Meshes? 3. Should we move the classes you've written into a new xmsmesh.py?

And one minor observation, the changes to requirements.txt are unnecessary now but won't do any harm.

**Comment by philippjfr** [comment]
Does this supersede #298?

**Comment by kcpevey** [comment]
> Does this supersede #298?  
  
Yes, I had a merge conflict and then managed to make a mess of things and I wasn't sure how to undo my mess so I just started over...

**Comment by kcpevey** [comment]
Whenever I use `python setup.py develop` with earthsim, pip doesn't recognize some of the required packages that ARE ALREADY in my env. So it ends up double installing things like Bokeh and it trashes my env because then both conda and pip are confused about what its in my env and I can't remove them without both of them getting confused. Have you seen this?

**Comment by jbednar** [comment]
I think it's safer to use `python setup.py develop --no-deps` or `pip install -e . --no-deps` to avoid pulling in bogus installations like that.

**Comment by kcpevey** [comment]
@jbednar Is that standard practice? It isn't something we can fix in the setup.py file?

**Comment by philippjfr** [comment]
I always use ``--no-deps`` with conda personally, not entirely sure why it doesn't recognize the dependencies but we should really never allow dependencies to be satisfied by ``setup.py develop`` so we should recommend that regardless.

**Comment by kcpevey** [comment]
@philippjfr I'm moving the classes into an `xmsmesh.py` file. Unfortunately I just trashed my env so I have create a new one before I can test. I'll ping you when I'm ready for review.

**Comment by kcpevey** [comment]
> And one minor observation, the changes to requirements.txt are unnecessary now but won't do any harm.   
  
I didn't change `requirements.txt`, which I dont think exists anymore, but I did update `dependencies.txt`. Why would that be unnecessary?

**Comment by philippjfr** [comment]
Sorry got confused, but dependencies.txt is also no longer really necessary because dependencies the authoritative source for dependencies is now setup.py. That said the developer instructions probably need updating to describe how to use that to set up an env, which basically just boils down to this command:

```
doit env_create -c pyviz/label/earthsim -c pyviz/label/dev -c defaults -c erdc -c conda-forge --name=earthsim --python=3.6
```

**Comment by philippjfr** [comment]
That also means you should add all those xms packages to the setup.py

**Comment by kcpevey** [comment]
It looks like the whole `Getting Started` page needs to be reworked to convey that there is a conda package available for general users and the command you listed above for developers.

**Comment by kcpevey** [comment]
@philippjfr @jbednar If you have strong feelings about how the getting started page gets worded, then I'll leave that to you. Otherwise, I don't mind revising it.

**Comment by philippjfr** [comment]
>If you have strong feelings about how the getting started page gets worded, then I'll leave that to you. Otherwise, I don't mind revising it.

I'd be happy for you to make an initial cut and then we can make any edits later.

**Comment by kcpevey** [comment]
If you install from `conda install -c conda-forge earthsim` you don't need the repo and doit command, right?

**Comment by philippjfr** [comment]
>If you install from conda install -c conda-forge earthsim you don't need the repo and doit command, right?

Correct, at least once we've finally released again.

**Comment by kcpevey** [comment]
@philippjfr ready for review.   
  
I reorganized the getting started page, but you should probably go over those instructions closely and make sure that I have everything right.

**Comment by philippjfr** [comment]
The updates look good to me. I'll do some testing soon and then hopefully cut a release by Monday.

**Comment by kcpevey** [comment]
Almost forgot, `python -c "import earthsim ; earthsim examples"` wouldn't work for me when I got the package from conda. The only other solution I could see would be to launch that command from the environment folder. Certainly there is a better command?

**Comment by philippjfr** [comment]
Oh yeah, ``python -c "import earthsim ; earthsim examples"`` doesn't seem right, shouldn't that simply be ``earthsim examples``?

**Comment by kcpevey** [comment]
even with earthsim in my environment, it wouldn't recognize the command `earthsim`. That command only works from inside of the repository folder.

**Comment by kcpevey** [comment]
That becomes an issue when you've install it via conda instead of the repos

**Comment by philippjfr** [comment]
``python -m "earthsim examples"`` then.

**Comment by philippjfr** [comment]
>That becomes an issue when you've installed it via conda instead of the repo

I'll fix that too.

**Comment by philippjfr** [comment]
Tests are failing because the aquaveo channel needs to be added to the .travis.yml and appveyor.yml to satisfy the xms dependencies.

**Comment by kcpevey** [comment]
My apologies. A lot of this is new to me!

**Comment by philippjfr** [comment]
>My apologies. A lot of this is new to me!

No problem, thanks for being so patient and making all these changes!

**Comment by philippjfr** [comment]
@kcpevey Do you know if aquaveo will make OSX packages for xmsmesh & co. available?

**Comment by philippjfr** [comment]
Actually, they do appear to exist, not sure why travis isn't picking up on them.

**Comment by philippjfr** [comment]
Thanks @kcpevey! Glad to have gotten rid of the filligree dependency.

**Pull request merged**
